api/v1/__init__.py
#!/usr/bin/env python3
from flask import Blueprint
from flask_restful import Api

from .resources.auth import AuthToken
from .resources.password import SelfPassword, OtherPassword
from .resources.team import Team, TeamList
from .resources.token import SelfMachineToken, OtherMachineToken


class CustomApi(Api):
    def handle_error(self, e):
        return {"message": str(e), "details": e.data}, e.code


def create_blueprint(oidc):
    api = CustomApi(catch_all_404s=True)

    api.add_resource(AuthToken(oidc), "/auth/token")

    api.add_resource(TeamList, "/team")
    api.add_resource(Team, "/team/<string:team>")

    api.add_resource(SelfPassword, "/password/<string:hostname>")
    api.add_resource(OtherPassword, "/password/<string:hostname>/<string:team>")

    api.add_resource(SelfMachineToken, "/token/<string:token>")
    api.add_resource(OtherMachineToken, "/token/<string:token>/<string:team>")

    bp = Blueprint("api_v1", __name__)
    api.init_app(bp)

    return bp

api/v1/resources/auth.py
#!/usr/bin/env python3
from flask_restful import Resource, abort
from flask import request

from utils.authentication import new_token

from sentry_sdk import capture_exception


def AuthToken(oidc):
    class wrapper(Resource):
        @oidc.require_login
        def get(self):
            try:
                client = oidc.user_getfield("name")
                team = oidc.user_getfield("team")
                roles = oidc.user_getfield("roles") or []

                return {"token": new_token(client, team, roles, 30).decode("utf-8")}
            except Exception as ex:
                capture_exception(ex)
                abort(500)

    return wrapper

app.py
#!/usr/bin/env python3
import os
import logging

from flask import Flask
from flask_oidc import OpenIDConnect

import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    integrations=[FlaskIntegration()],
    send_default_pii=True,
)


def create_app():
    app = Flask(__name__)
    app.secret_key = os.getenv("FLASK_SECRET")
    if app.secret_key is None:
        raise ValueError("A Flask secret is needed (FLASK_SECRET envvar)")

    app.config.update(
        {
            "ERROR_404_HELP": False,
            "BUNDLE_ERRORS": True,
            "LOGGING_LEVEL": logging.DEBUG,
            # OIDC
            "OIDC_CLIENT_SECRETS": "client_secrets.json",
            "OIDC_SCOPES": ["openid", "email", "profile"],
            # "OIDC_COOKIE_SECURE": False,
        }
    )

    oidc = OpenIDConnect(app)

    import api.v1
    import views.root

    app.register_blueprint(api.v1.create_blueprint(oidc), url_prefix="/api/v1")
    app.register_blueprint(views.root.create_blueprint(oidc), url_prefix="/")

    return app

views/root.py
#!/usr/bin/env python3
from flask import Blueprint, render_template, redirect, request, abort
from utils.authentication import require_roles


def create_blueprint(oidc):
    bp = Blueprint("root", __name__)

    @bp.route("/")
    @oidc.require_login
    @require_roles(oidc, ["viewer"])
    def index():
        team = oidc.user_getfield("team")
        roles = oidc.user_getfield("roles") or []
        if team is None:
            abort(403)

        return render_template("index.html", team=team, roles=roles)

    @bp.route("/logout")
    def logout():
        if oidc.user_loggedin:
            oidc.logout()
            return redirect(
                "{logout_endpoint}?redirect_uri={redirect_uri}".format(
                    logout_endpoint=oidc.client_secrets.get("end_session_uri"),
                    redirect_uri=request.url,
                )
            )
        else:
            return render_template("logout.html")

    @bp.errorhandler(500)
    def server_error(error):
        return render_template("internal_error.html"), 500

    return bp

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/thirdparty/bootstrap-4.3.1.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/thirdparty/material-icons.css') }}">

    <script src="{{ url_for('static', filename='js/thirdparty/jquery-3.3.1.min.js') }}"></script>

    <title>{% block page_title %}{% endblock %} - SC Utilities</title>
    {% block meta %}{% endblock %}
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <script src="{{ url_for('static', filename='js/thirdparty/popper-1.14.7.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/thirdparty/bootstrap-4.3.1.min.js') }}"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block page_title %}ESRF root password retriever{% endblock %}
{% block meta %}
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  <script src="{{ url_for('static', filename='js/thirdparty/clipboard-2.0.0.min.js') }}"></script>
{% endblock %}
{% block content %}
  <div class="text-center">
    {% if request.host != "rootriever.esrf.fr" %}
    <div class="modal fade" id="deprecatedModal" tabindex="-1" role="dialog" aria-labelledby="deprecatedModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deprecatedModalTitle">Woof!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            This tool is now accessible from <a href="https://rootriever.esrf.fr" class="alert-link">https://rootriever.esrf.fr</a>.
            Please update your bookmarks accordingly.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <script>
      $(function() {
        $('#deprecatedModal').modal('show')
      });
    </script>
    {% endif %}

    <div class="modal fade" id="sudoModal" tabindex="-1" role="dialog" aria-labelledby="sudoModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="sudoModalTitle">Quick tips on sudo</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body text-left">
            <section class="mb-3">
              <h6 class="font-weight-bold">How to use sudo</h6>
              <div class="mb-2">
                Just prefix your command with <kbd>sudo</kbd>.
              </div>
              <samp class="console-output">
                <span class="ps1-host ps1-user">user@remotehost</span>:<span class="ps1-dir">~</span>$ sudo apt update
              </samp>
            </section>

            <section class="mb-3">
              <h6 class="font-weight-bold">X11 forwarding with sudo</h6>
              <div class="mb-2">
                X11 is designed not to allow anyone to connect to the socket.
                To do this, it uses a simple cookie system. You can import it after invoking sudo.
              </div>
              <samp class="console-output">
                <span class="ps1-host ps1-user">user@mycomputer</span>:<span class="ps1-dir">~</span>$ ssh -X user@remotehost<br>
                <span class="ps1-host ps1-user">user@remotehost</span>:<span class="ps1-dir">~</span>$ echo $DISPLAY<br>
                localhost:<strong>11.0</strong><br>
                <span class="ps1-host ps1-user">user@remotehost</span>:<span class="ps1-dir">~</span>$ xauth list<br>
                remotehost/unix:10  MIT-MAGIC-COOKIE-1  479549ad9a1cf35d7aa9dc7354e36ddb<br>
                remotehost/unix:<strong>11</strong>  MIT-MAGIC-COOKIE-1  <strong>13c9466250e81b3b656406bc9dc784b9</strong><br>
                <span class="ps1-host ps1-user">user@remotehost</span>:<span class="ps1-dir">~</span>$ sudo -i<br>
                [sudo] password for user:<br>
                <span class="ps1-host ps1-root">root@remotehost</span>:<span class="ps1-dir">~</span># xauth add remotehost/unix:11  MIT-MAGIC-COOKIE-1  <strong>13c9466250e81b3b656406bc9dc784b9</strong><br>
                <span class="ps1-host ps1-root">root@remotehost</span>:<span class="ps1-dir">~</span># xclock
              </samp>
            </section>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <strong>Here be dragons!</strong>
      Please note that this tool is intended for use in emergencies only!<br>
      In general cases, you must use your account with <a href="#" data-toggle="modal" data-target="#sudoModal">sudo</a>.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <img class="mb-4" src="{{ url_for('static', filename='img/logo.png') }}" alt="ESRF Logo" height="256">
    <h1 class="h3 mb-3 font-weight-normal">ESRF root password retriever</h1>
    <p class="lead">{{ team }} root passwords are unique and changed regularly</p>

    <form class="form-request" id="passwordForm" onsubmit="return false;">
      <div class="form-group mt-2">
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="passwordHostname" name="requestTypeGroup" class="custom-control-input" data-bind="checked: requestType" value="hostname">
          <label class="custom-control-label" for="passwordHostname">I know the machine name</label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="passwordToken" name="requestTypeGroup" class="custom-control-input" data-bind="checked: requestType" value="token">
          <label class="custom-control-label" for="passwordToken">I have a token</label>
        </div>
      </div>

      <div class="input-group">
        <input type="text" class="form-control" id="request" data-bind='value: request, enable: ready, valueUpdate: "afterkeydown", css: style, attr: { placeholder: placeholder }'>

        <!-- Not using visible data-binding to keep the round border of input -->
        <!-- ko if: othernames().length > 0 || adminUI -->
        <div class="input-group-append">
          <!-- ko foreach: othernames -->
          <button class="btn btn-outline-secondary" type="button" data-bind="text: hostname, click: follow"></button>
          <!-- /ko -->
          <!-- ko if: adminUI -->
          <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-bind="text: selectedTeam"></button>
          <div class="dropdown-menu" data-bind="foreach: teams">
            <a class="dropdown-item" href="#" data-bind="text: $data, click: $parent.selectTeam"></a>
          </div>
          <!-- /ko -->
        </div>
        <!-- /ko -->
      </div>

      <div class="alert alert-danger my-3" role="alert" data-bind="visible: authApi.error">
        <strong data-bind="text: authApi.errorMessage"></strong><br>
        Please refresh the page, if the problem persists, contact the UNIX service.
      </div>

      <div class="form-group mt-3 mb-3" data-bind="visible: password, with: password">
        <div class="input-group mb-1">
          <input class="form-control" type="password" data-bind="value: password, attr: { type: $root.passwordDisplay }" readonly />
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" data-bind="click: $root.togglePassword">
              <i class="material-icons" style="font-size: 1em;">remove_red_eye</i>
            </button>
            <button id="copy2cpbd" class="btn btn-outline-secondary" type="button">
              <i class="material-icons" style="font-size: 1em;">assignment</i>
            </button>
          </div>
        </div>
        <p class="lead text-muted" data-bind="visible: expire_ts">Expire at <span data-bind="text: expiration_full"></span></p>
      </div>

      <div class="form-group mt-3" data-bind="visible: previous().length">
        <p class="lead text-muted"><a data-toggle="collapse" href="#prevPasswords" role="button">Previous passwords</a></p>
        <ul id="prevPasswords" class="list-group collapse" data-bind="foreach: previous">
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <span data-bind="text: password"></span>
            <small data-bind="text: expiration_date" class="text-muted"></small>
          </li>
        </ul>
      </div>

    </form>
  </div>

  <div class="fixed-bottom text-right m-2">
    <a class="btn btn-danger" href="{{ url_for('root.logout') }}" role="button">
      <i class="material-icons" style="font-size: 1em;">logout</i>
    </a>
  </div>

  <script src="{{ url_for('static', filename='js/thirdparty/knockout-3.4.2.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/auth.js') }}"></script>
  <script src="{{ url_for('static', filename='js/password.js') }}"></script>
  <script>
      authApi = new Authentication();

      var hostname;
      if (window.location.hash) {
          hostname = window.location.hash.substring(1);
      }

      passVM = new GeneratorViewModel(authApi, hostname, function(h) {
          window.location.hash = h || '';
      }, {{ team | tojson}}, {{ 'true' if 'admin' in roles else 'false' }});

      ko.applyBindings(passVM, $('#passwordForm')[0]);
      authApi.auth();

      var clipboard = new ClipboardJS('#copy2cpbd', {
          text: function(trigger) {
              return passVM.password().password();
          }
      });
  </script>
{% endblock %}

templates/logout.html
{% extends "base.html" %}
{% block page_title %}Logout successful{% endblock %}
{% block meta %}
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="text-center">
    <h1 class="h2">You are now logged out</h1>
    <p class="lead">Come back soon!</p>
  </div>
{% endblock %}